name: Test Automation Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas BDD Behave
      run: |
        behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results features/

    - name: Generar Reporte HTML
      if: always()
      run: |
        python generar_reporte.py

    - name: Subir reporte como artefacto
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: reporte-ejecucion-html
        path: reports/reporte.html